# Generated by Django 3.1.3 on 2020-11-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestateproperty',
            options={'verbose_name_plural': 'Real Estate Properties'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name_plural': 'History'},
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='price',
            field=models.IntegerField(),
        ),
    ]
